#!/bin/bash


addpath () {
  x="$1"
  IFS=:
  set -- $PATH
  IFS=
  while test "$#" -gt 0 ; do
    if test "$1" = "$x" ; then
      return
    fi
    shift
  done
  PATH="${x}:$PATH"
}

if test -z "$PATH" ; then
  PATH=/bin
fi

addpath /bin
addpath /usr/bin
addpath /command
export PATH
# nohup /sbin/entrypoint.sh &
# nohup mysqld &
nohup /opt/hbase-server &
# # nohup /app/code-server/bin/code-server \
# #     --install-extension /ms-python.python-2022.17.12941045.vsix --extensions-dir /config/extensions &
# # Now we're good: s6-overlay-suexec is accessible via PATH, as are
# # all our binaries.
# # Run preinit as root, then run stage0 as the container's user (can be
# # root, can be a normal user).

exec s6-overlay-suexec \
  ' /package/admin/s6-overlay-3.1.0.1/libexec/preinit' \
  '' \
  /package/admin/s6-overlay-3.1.0.1/libexec/stage0 \
  "$@"
sleep infinity